[package]
name = "dstore"
version = "0.1.0"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"

[[bin]]
name = "global"
path = "src/global.rs"

[[bin]]
name = "local"
path = "src/local.rs"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
bytes = "1"
tonic = "0.3"
prost = "0.6"

[build-dependencies]
tonic-build = "0.3.0"